[build-system]
requires = ["setuptools >= 77.0.3", "httpx"]
build-backend = "setuptools.build_meta"

[project]
name = "aqdrop"
dynamic = ["version"]
authors = [
    { name="Evan Caplinger", email="ecaplinger@lbl.gov" },
    { name="Jan Balewski", email="balewski@lbl.gov" }
]
description = "Thin client SDK for AQDROP API"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "BSD-3-Clause"
license-files = ["license.txt"]

dependencies = [
    "authlib>=1.6.0",
    "httpx>=0.28.1",
    "requests>=2.32.0",
    "tabulate>=0.10.0",
]

[project.scripts]
aqdrop = "aqdrop.cli:main"
aqdrop-generate-sfapi-token = "aqdrop.generate_sfapi_token:main"
aqdrop-operator = "aqdrop_operator.operator_daemon:cli"
aqdrop-run-qiskit = "aqdrop_operator.job_run_qiskit:cli"
aqdrop-run-qpu = "aqdrop_operator.job_run_qpu:cli"

[project.optional-dependencies]
test = [
    "pytest>=8"
]
qiskit = [
    "qiskit[core]>=2.3.1,<3"
]
operator = [
    "lbl-qubic",
    "PyYAML>=6",
    "qiskit[core]>=2.3.1,<3",
    "qiskit-aer",
    "qiskit-ibm-runtime",
    "quantum-calibration",
]

[project.urls]
Repository = "https://github.com/NERSC/aqdrop-client"

[tool.setuptools.dynamic]
version = {attr = "aqdrop.__version__"}

[tool.setuptools.packages.find]
include = ["aqdrop*"]
exclude = ["admin*", "examples*"]
